org.gradle.jvmargs=-Xmx4G -Xss4m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
neo_version_range=[21.1.219,)
loader_version_range=[1,)

## Mod Properties
mod_id=biomorphosis
mod_name=Biomorphosis
mod_license=Arc`s License of Common Sense
mod_version=26.1.2
mod_group_id=com.arcanc.biomorphosis
mod_authors=ArcAnc, Qriq
mod_description=Biomorphosis - a mod about mutations and evolution, where you control an organic ecosystem, creating structures and creatures from living matter. Harness biomass to develop your colony, but be prepared for the dangers your experiments may bring

pulselib_version=1.21.1-1.0.7
jei_version=19.27.0.340
jade_version=15.10.5+neoforge